language: java

jdk:
  - oraclejdk8

after_success:
  - mvn clean -PEnableReportPlugins cobertura:cobertura coveralls:report com.srcclr:srcclr-maven-plugin:scan

cache:
  directories:
    - '$HOME/.m2/repository'
